### ISSUE TITLE
When selection includes 2 staves & last measure plugin does not see bottom staff

### ISSUE THREAD

**Issue by elsewhere37** [ellejohara/newretrograde#5]
Cursor.tick is reset to 0 after reading last measure in staff 1.
(If you need to contact me: dirk.elseviers@telenet.be)

**Comment by elsewhere37** [comment]
I think I found the bug:
You need to add

if(cursor.tick == 0) {
    cursor.rewind(1); // rewind to get additional voices
}

at lines 86, 185 & 193

i.e. after:
for(var trackNum in tracks) {

and after the 2 cursor.next() statements below

but have not tested extensively

**Comment by elsewhere37** [comment]
There are still problems. please look at my new post on https://musescore.org/en/node/333755

**Comment by ellejohara** [comment]
Fixed in 3.0.4.
